import Foundation

/// Framebuffer generated by self-authored x86-64 guest code and Misaki's
/// original 2D graphics protocol. This is not PS4/GNM/GCN emulation.
struct NativeGraphics19Frame {
    let status: Int32
    let frameIndex: UInt32
    let width: UInt32
    let height: UInt32
    let commands: UInt32
    let rectangles: UInt32
    let sprites: UInt32
    let guestInstructions: UInt32
    let guestServiceCalls: UInt32
    let guestHalted: Bool
    let stackRestored: Bool
    let spriteX: UInt32
    let spriteY: UInt32
    let checksum: UInt64
    let pixels: [UInt8]

    var passed: Bool {
        status == 0 && width == 320 && height == 180 &&
        commands == 7 && rectangles == 4 && sprites == 1 &&
        guestInstructions == 6 && guestServiceCalls == 1 &&
        guestHalted && stackRestored && spriteX == 32 + 2 * (frameIndex % 90) &&
        spriteY == 78 && checksum != 0 && pixels.count == 320 * 180 * 4
    }
}

enum NativeGraphics19API {
    static func makeFrame(index: UInt32 = 0) -> NativeGraphics19Frame {
        let capacity = 320 * 180 * 4
        var buffer = [UInt8](repeating: 0, count: capacity)
        var report = MisakiGPU19Report()
        let code: Int32 = buffer.withUnsafeMutableBufferPointer { pointer in
            misaki_gpu19_render(index, pointer.baseAddress, pointer.count, &report)
        }
        return NativeGraphics19Frame(
            status: code, frameIndex: report.frame_index,
            width: report.width, height: report.height,
            commands: report.command_count, rectangles: report.rectangles,
            sprites: report.sprites, guestInstructions: report.guest_instructions,
            guestServiceCalls: report.guest_service_calls,
            guestHalted: report.guest_halted == 1,
            stackRestored: report.stack_restored == 1,
            spriteX: report.sprite_x, spriteY: report.sprite_y,
            checksum: report.checksum,
            pixels: code == 0 && Int(report.bytes_written) == capacity ? buffer : []
        )
    }
}
